# action.yml
name: 'OpenAPI Generator'
description: 'Geenerate client from open api document'
inputs:
  input: 
    description: Path to open api document 
    required: true
    default: /github/workspace/swagger.json
  config: 
    description: Path to config file
    required: true
  generator: 
    description: Generator 
    required: true
    default: typescript-fetch
  output: 
    description: Path to generate files to
    required: true
    default: /github/workspace/output
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - generate
    - "-i"
    - ${{ inputs.input }}
    - "-o"
    - ${{ inputs.output }}
    - "-g"
    - ${{ inputs.generator }}
    - "-c"
    - ${{ inputs.config }}
    # - "-t"
    # - "/template/typescript-fetch"
    # - "--additional-properties=npmName=@crochik/auto-pi,npmVersion=0.1.4"    
